name: dev-cicd
on:
  push:
    branches:
      - 'dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
        with:
          ref: 'dev'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/oval-operator-service:dev
  deployment:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: Prep helm chart
        run: |
          mv ./kubernetes/helm-chart/operator-service/Chart.yaml ./kubernetes/helm-chart/operator-service/Chart.old.yaml &&
          cat ./kubernetes/helm-chart/operator-service/Chart.old.yaml | grep -v appVersion > ./kubernetes/helm-chart/operator-service/Chart.yaml &&
          echo -e "\r\nappVersion: v${GITHUB_REF##*/}\r\n" >> ./kubernetes/helm-chart/operator-service/Chart.yaml &&
          cat ./kubernetes/helm-chart/operator-service/Chart.yaml
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm upgrade operator-service ./kubernetes/helm-chart/operator-service --install --wait --atomic --namespace=dev-oval --values=./kubernetes/helm-chart/operator-service/dev-values.yaml
          kubeconfig: '${{ secrets.DEV_KUBECONFIG }}'
